name: ServerJava17

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Downloading Java.
      run: |
        Invoke-WebRequest https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.12.01.zip -OutFile server.zip
    - name: extrack server
      run:
        Expand-Archive server.zip
    - name: run server
      run: .\server\bedrock_server
